### PR TITLE
Add one test for withdraw_confirm

### PR DESCRIPTION
**Pull request by axelchalon**
I added one test for checking the amount of confirmations in withdraw_confirm, but I can't think of other things I could test with the current setup... could you give me some more pointers maybe?

### CODE REVIEW

**Comment by axelchalon** [comment]
Closes #8

**Comment by debris** [comment]
That's a good start. Uou can check multiple several more things ;)

- `Database::testnet_contract_address`
- `testnet::confirmations`

Then you can do more comprehensive tests. eg. what happens when `eth_getLogs` returns some logs. Similar to [deposit_relay_single_log](https://github.com/paritytech/bridge/blob/3009632a6bb7ffcf77d44ceb155c2dadf76a84fd/tests/tests/deposit_relay.rs#L70). Test data was for this test was taken from [here](https://github.com/paritytech/bridge/blob/3009632a6bb7ffcf77d44ceb155c2dadf76a84fd/bridge/src/bridge/deposit_relay.rs#L119-L135). Accordingly you can use those [two tests](https://github.com/paritytech/bridge/blob/3009632a6bb7ffcf77d44ceb155c2dadf76a84fd/bridge/src/bridge/withdraw_confirm.rs#L154-L181) data to write tests for comprehensive tests for `withdraw_confirm`.

Then there are many more things which needs to be checked:

- existance of rpc calls
- order of rpc calls
- validity of rpc payloads
- `testnet::account`


I will also extend the macro with new fields: `transactions`, which will allow changing [TransactionConfig](https://github.com/paritytech/bridge/blob/3009632a6bb7ffcf77d44ceb155c2dadf76a84fd/bridge/src/config.rs#L75) properties

**Comment by debris** [comment]
open #8

**Comment by debris** [comment]
I've added few more deposit_relay tests in #20

**Comment by axelchalon** [comment]
Okay! Thanks :) Added one test for the contact address https://github.com/paritytech/bridge/pull/21; didn't know how to test testnet::confirmations in a way that would be different from what's already been tested...
I'll have a look at the rest!

**Pull request merged**
